# Generated by Django 5.2.13 on 2026-04-27 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdb_id', models.IntegerField(unique=True)),
                ('title', models.CharField(max_length=255)),
                ('poster_url', models.URLField(blank=True, max_length=500, null=True)),
                ('category', models.CharField(default='movie', max_length=100)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
